Python For Data Science

Numpy

Numpy is a library for working with arrays and matrices. It is the fundamental package for scientific computing in Python. Numpy is optimized to be fast and memory efficient, and supports a large number of numerical functions.

In [69]:
import numpy as np

In [70]:
a = np.array([1, 2, 3, 4, 5], dtype=np.int64)
b = np.array((1, 2, 3, 4, 5), dtype=np.float64)

In [71]:
print(a)
print(b)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [72]:
type(a)

numpy.ndarray

In [73]:
type(b)

numpy.ndarray

dtype method return dynamic type of numpy array

In [74]:
a.dtype

dtype('int64')

In [75]:
b.dtype

dtype('float64')

Numpy (Dimensions)

In [76]:
a = np.array([[1,2,3],[4,5,6]])

In [77]:
b = np.array([[1,2,3],[4,5,6,7]])

C:\Users\Phanxv\AppData\Local\Temp\ipykernel_17304\4080802680.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b = np.array([[1,2,3],[4,5,6,7]])


The multidimensional arrays must have a consistent number of index to be able to behave as a multidimensional array

In [78]:
b = np.array([[1,2,3,4],[5,6,7,8]])

ndim is number of dimensions in array

In [79]:
print(a.ndim)
print(b.ndim)

2
2


In [80]:
print(a[1,2])
print(b[1,3])

6
8


In [81]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c.ndim)
print(c[1,0,2])

3
9


shape describe the shape outline of the array

(number of 2d array, number of 1d array per 2d array, number of element per 1 d array)

In [82]:
c.shape

(2, 2, 3)

size is total numbere of element in an array

In [83]:
c.size

12

nbyte is the number of byte taken by an array in memory

In [84]:
c.nbytes

48

Different way to create differnt kind of array using Numpy

np.zeros is for creating zeros array

In [85]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


np.arange(x) is for creating an array with element from 0 to x-1

np.arange(x,y) is for creating an array with element from x to y-1

np.arange(x,y,z) is for creating an array with element from x to y-1 with z step

In [86]:
a = np.arange(20)
print(a)
b = np.arange(10,20)
print(b)
c = np.arange(10,20,2)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


np.random is to rearrange array in random

In [87]:
a = np.random.permutation(np.arange(10))
print(a)

[1 4 5 8 0 9 6 2 7 3]


In [88]:
b = np.random.randint(1,100,(3,3))
print(b)

[[98 16 39]
 [97 12 81]
 [15 44 30]]


np.reshape is for reshaping array

In [89]:
a = np.arange(10)
b = a.reshape(2,5)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Slicing Array using Numpy

array[start:stop:step]

slicing array using numpy is different from slicing a primitive array

in that sliced array will not copy the value but reference it

In [90]:
a = np.arange(20)
b = a[5:20]

In [91]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [92]:
b[10] = 69

When changing value in b you can noticed that value in a also change

In [93]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 69 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14 69 16 17 18 19]


slice array by copy (not refernce) by copy() method

In [94]:
b = a[5:20].copy()

In [95]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 69 16 17 18 19]
[ 5  6  7  8  9 10 11 12 13 14 69 16 17 18 19]


when changing value in b the value in a will not change because this is slicing by copy and not reference

In [96]:
b[10] = 420

In [97]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 69 16 17 18 19]
[  5   6   7   8   9  10  11  12  13  14 420  16  17  18  19]


Reversing array with slicing by step -1

In [98]:
a = np.arange(20)
b = a[::-1]

In [99]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


Finding array where argument is true

using np.argwhere(argument)

In [110]:
np.argwhere(a>15)

array([[4]], dtype=int64)

In [112]:
np.argwhere(b==15)[0][0]

4